services:
  undb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: undb
    ports:
      - 3721:3721
    environment:
      - UNDB_BASE_URL=http://localhost:3721
      - UNDB_DISABLE_REGISTRATION=true
      - UNDB_ADMIN_EMAIL=${ADMIN_EMAIL}
      - UNDB_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./undb.sqlite:/usr/src/app/undb.sqlite
      - ${STORAGE_DIR}:/usr/src/app/.undb/storage
